{% set version = "1.3.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-entropy
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/entropy_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/entropy/entropy_{{ version }}.tar.gz
  sha256: 0af71dc25ebbd2b03136c44d33359e67811e5d3b262c91791f87a5c890d7103a

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('entropy')"           # [not win]
    - "\"%R%\" -e \"library('entropy')\""  # [win]

about:
  home: http://strimmerlab.org/software/entropy/
  license: GPL-3.0-or-later
  summary: This package implements various estimators of entropy, such as the shrinkage estimator by Hausser and Strimmer, the maximum likelihood  and the Millow-Madow estimator, various Bayesian estimators, and the  Chao-Shen estimator.  It also offers an R interface to the NSB estimator. Furthermore, it provides functions
    for estimating Kullback-Leibler divergence, chi-squared, mutual information, and chi-squared statistic of independence. In addition there are functions for discretizing continuous random variables.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
