# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ewN7P308ZkC89UNZD6O1Afqd1nNZZJzP66QJyhxIh3V5JxTqGp+pLSO6oF+pU6/Hppv2Ijx3uBHyIH5CfI4Dr876mNyUMeojwAsjawQCgaggTa5LRHGxAMSWSaKTGcPxUi+kdiflmCf29eHyXav+4VXf1AGUmn+UmwQ0zL4LlwiaB8tWQNmktnYiVVpghfwxRjPPd8zStnnVDWxeASGUMl5KvSsscbbpmbs7cygJ8O7ZxAgyEUGSHMMikaBugBYvC/nhEobZn316p1NDV1Dz1u9PIHrKVimrZP6ypznNOQn+gAQkDiN7oiuBO9sSr4DQHihFJxmDd7Y5CqO+PaANJPHXf9T71leIycRvS47FLJ8B8MpAy0Q/UWQdNUWD2ZUgmr1CohX2zB41kj42V4ZbPH++cybsBBnnhcKkpFTHQRmbjIK7O7BQOTQJrS3X3aXAnA/wn2b+NSPPw07qeqP4cbMh3cUn1v9deb3rq69Y5Zm5JJWit1KNy6z0YoLYSCLUDgO1WddYksbjpUfA80TymlLvRGX3vfygOx6fv8C9KFCVwteWgU+aX1gyTyBhokx2TtT20JO00Mu6zPpwHvUtQAI+CEu9O3dvgmPxG3p9xfsCJHrPdddmelllWRhzkH8nI/qaZlhZHJGv8r3IhYCGYO7Y8SeuIXiuh4qZJvd/GZU="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
