travis:
  secure:
    BINSTAR_TOKEN: ewN7P308ZkC89UNZD6O1Afqd1nNZZJzP66QJyhxIh3V5JxTqGp+pLSO6oF+pU6/Hppv2Ijx3uBHyIH5CfI4Dr876mNyUMeojwAsjawQCgaggTa5LRHGxAMSWSaKTGcPxUi+kdiflmCf29eHyXav+4VXf1AGUmn+UmwQ0zL4LlwiaB8tWQNmktnYiVVpghfwxRjPPd8zStnnVDWxeASGUMl5KvSsscbbpmbs7cygJ8O7ZxAgyEUGSHMMikaBugBYvC/nhEobZn316p1NDV1Dz1u9PIHrKVimrZP6ypznNOQn+gAQkDiN7oiuBO9sSr4DQHihFJxmDd7Y5CqO+PaANJPHXf9T71leIycRvS47FLJ8B8MpAy0Q/UWQdNUWD2ZUgmr1CohX2zB41kj42V4ZbPH++cybsBBnnhcKkpFTHQRmbjIK7O7BQOTQJrS3X3aXAnA/wn2b+NSPPw07qeqP4cbMh3cUn1v9deb3rq69Y5Zm5JJWit1KNy6z0YoLYSCLUDgO1WddYksbjpUfA80TymlLvRGX3vfygOx6fv8C9KFCVwteWgU+aX1gyTyBhokx2TtT20JO00Mu6zPpwHvUtQAI+CEu9O3dvgmPxG3p9xfsCJHrPdddmelllWRhzkH8nI/qaZlhZHJGv8r3IhYCGYO7Y8SeuIXiuh4qZJvd/GZU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
